# Generated by Django 2.0.5 on 2018-05-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.TextField(default='', verbose_name='Body'),
            preserve_default=False,
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='body',
        ),
    ]
