# Generated by Django 2.0.5 on 2018-05-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_commenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='commenthistory',
            name='trashed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Removal date'),
        ),
    ]
