# Generated by Django 2.0.5 on 2018-05-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_commenthistory_trashed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commenthistory',
            name='trashed_at',
        ),
        migrations.AddField(
            model_name='comment',
            name='trashed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Removal date'),
        ),
    ]
