# Generated by Django 2.0.5 on 2018-05-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0007_auto_20180512_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='commenthistory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
